Cookbook/Controllers/CookbookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using Cookbook.Models;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.SimpleEmail;
using Amazon.SimpleEmail.Model;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;


namespace Cookbook.Controllers
{
    [Authorize]
    public class CookbookController : Controller
    {
        private CookbookDBModelsDataContext db = new CookbookDBModelsDataContext();
        private static UsersContext userDb = new UsersContext();
        private AmazonS3 s3client = new AmazonS3Client();

        /// <summary>
        /// Returns user's own cookbook.
        /// </summary>
        /// <param name="page">The page number the user currently is viewing</param>
        /// <returns></returns>
        public ActionResult Index(Nullable<int> page)
        {
            ViewBag.UserId = WebSecurity.CurrentUserId;

            var recipes = GetRecipes(WebSecurity.CurrentUserId);

            if (page == null || page < 1)
                page = 1;
            List<ViewPostModel> sortedPosts = GetCombinedPosts(GetRecipes(WebSecurity.CurrentUserId),
                                                               GetBlogPosts(WebSecurity.CurrentUserId),
                                                               (int)page, ViewBag);

            return View(sortedPosts);
        }

        /// <summary>
        /// View another user's cookbook
        /// </summary>
        /// <param name="userId">The user you're looking at</param>
        /// <param name="page">Current page number</param>
        /// <returns></returns>
        public ActionResult ViewCookbook(int userId, Nullable<int> page)
        {
            try
            {
                //if the user id is the logged in user's, redirect to index
                if (userId == (int)Membership.GetUser().ProviderUserKey)
                {
                    return RedirectToAction("Index");
                }

                User_Subscriber us = new User_Subscriber
                {
                    UserId = (int)Membership.GetUser().ProviderUserKey,
                    SubscriberId = userId
                };

                if (db.User_Subscribers.Contains(us))
                {
                    ViewBag.IsSubscribed = true;
                }
                else
                {
                    ViewBag.IsSubscribed = false;
                }

                ViewBag.UserId = userId;
                ViewBag.Username = (from allUsers in userDb.UserProfiles
                                    where allUsers.UserId == userId
                                    select allUsers.UserName).First();

                if (page == null || page < 1)
                    page = 1;
                var sortedPosts = GetCombinedPosts(GetRecipes(userId), GetBlogPosts(userId), (int)page, ViewBag);

                return View(sortedPosts);
            }
            catch (InvalidOperationException e)
            {
                ViewBag.Error = "Error retrieving user profile";
                return View("Error");
            }
        }

        /// <summary>
        /// Grabs all recipes from a single user
        /// </summary>
        /// <param name="userId">the user to retrieve recipes from</param>
        /// <returns></returns>
        public List<Recipe> GetRecipes(int userId)
        {
            var recipes = (from allRecipes in db.Recipes
                           where allRecipes.UserID == userId
                           select allRecipes).ToList();
            return recipes;
        }

        /// <summary>
        /// Grabs all blog posts from a single user
        /// </summary>
        /// <param name="userId">the user to retrieve blog posts from</param>
        /// <returns></returns>
        public List<BlogPost> GetBlogPosts(int userId)
        {
            var posts = (from allPosts in db.BlogPosts
                         where allPosts.UserId == userId
                         select allPosts).ToList();
            return posts;
        }


        /// <summary>
        /// Retrieves a list of post view models (both recipes and blogs) and orders them by date (newest first).
        /// </summary>
        /// <param name="recipes">The recipes to create view models for</param>
        /// <param name="blogPosts">The blog posts to create view models for</param>
        /// <param name="page">The current page number</param>
        /// <param name="ViewBag"></param>
        /// <returns>Date ordered list of recipes/blogs</returns>
        public static List<ViewPostModel> GetCombinedPosts(List<Recipe> recipes, List<BlogPost> blogPosts,
                                                           int page, dynamic ViewBag)
        {

            CookbookDBModelsDataContext db = new CookbookDBModelsDataContext();
            UsersContext userDb = new UsersContext();

            List<ViewPostModel> postList = new List<ViewPostModel>();

            foreach (var recipe in recipes)
            {
                ViewRecipeModel recipeView = new ViewRecipeModel();
                recipeView.DateModified = recipe.DateModified;
                recipeView.FavoriteCount = recipe.FavoriteCount;
                recipeView.Instructions = recipe.Instructions;
                recipeView.LikeCount = recipe.LikeCount;

                var ingredients =
                    (from allIngredients in db.Ingredients
                     where allIngredients.RecipeId == recipe.RecipeID
                     select allIngredients.Name).ToList();
                recipeView.Ingredients = ingredients;

                var tags =
                    (from allTags in db.Recipe_Tags
                     where allTags.RecipeID == recipe.RecipeID
                     select allTags.Tag).ToList();
                recipeView.Tags = tags;

                ViewPostModel post = new ViewPostModel();
                post.DateCreated = recipe.DateCreated;
                post.RecipePost = recipeView;
                post.Username = (from userprofiles in userDb.UserProfiles
                                 where userprofiles.UserId == recipe.UserID
                                 select userprofiles.UserName).FirstOrDefault();
                post.ImageURL = recipe.ImageUrl;
                post.Title = recipe.Title;
                post.PostId = recipe.RecipeID;
                post.UserID = recipe.UserID;
                if (db.Recipe_Likers.Contains(new Recipe_Liker { UserId = WebSecurity.CurrentUserId, RecipeId = post.PostId }))
                {
                    post.Liked = true;
                }
                else
                {
                    post.Liked = false;
                }
                if (db.Recipe_Favoriters.Contains(new Recipe_Favoriter { UserId = WebSecurity.CurrentUserId, RecipeId = post.PostId }))
                {
                    post.RecipePost.Favorited = true;
                }
                else
                {
                    post.RecipePost.Favorited = false;
                }
                postList.Add(post);

            }

            foreach (var blog in blogPosts)
            {
                ViewBlogModel blogView = new ViewBlogModel();
                blogView.DateModified = blog.DateModified;
                blogView.LikeCount = blog.LikeCount;
                blogView.Post = blog.Post;

                var tags =
                    (from allTags in db.BlogPost_Tags
                     where allTags.BlogPostId == blog.BlogPostId
                     select allTags.Tag).ToList();
                blogView.Tags = tags;

                ViewPostModel post = new ViewPostModel();
                post.DateCreated = blog.DateCreated;
                post.BlogPost = blogView;
                post.Username = (from userprofiles in userDb.UserProfiles
                                 where userprofiles.UserId == blog.UserId
                                 select userprofiles.UserName).FirstOrDefault();
                post.ImageURL = blog.ImageUrl;
                post.Title = blog.Title;
                post.PostId = blog.BlogPostId;
                post.UserID = blog.UserId;
                if (db.BlogPost_Likers.Contains(new BlogPost_Liker { UserId = WebSecurity.CurrentUserId, BlogPostId = post.PostId }))
                {
                    post.Liked = true;
                }
                else
                {
                    post.Liked = false;
                }
                postList.Add(post);
            }


            int pageLength = 15;
            int startPage = (page - 1) * pageLength;
            ViewBag.Page = (int)page;
            ViewBag.LastPage = (int)Math.Ceiling((double)postList.Count() / pageLength);

            if (startPage < postList.Count)
            {
                if (startPage + pageLength - 1 >= postList.Count)
                {
                    pageLength = postList.Count - startPage;
                }

                return postList.OrderByDescending(p => p.DateCreated).ToList().GetRange(startPage, pageLength);
            }
            else
            {
                return new List<ViewPostModel>();//there are no results in this page, return an empty list
            }

        }

        /// <summary>
        /// Upload recipe page
        /// </summary>
        /// <returns></returns>
        public ActionResult UploadRecipe()
        {
            return View();
        }

        /// <summary>
        /// Enters uploaded recipe into database
        /// </summary>

Cookbook/Views/Cookbook/DeletePost.cshtml
@{
    ViewBag.Title = "DeletePost";
}

<h2>DeletePost</h2>

Cookbook/Views/Cookbook/DisplayFavorites.cshtml
@{
    ViewBag.Title = "Favorites";
}

<h4>@ViewBag.FavoriteCount people like this post</h4>

@if (ViewBag.Favoriters.Count != 0)
{
    <ul>
        @foreach (var favoriter in ViewBag.Favoriters)
        {
            <li>
                @favoriter
            </li>        
        }

    </ul>
}

Cookbook/Views/Cookbook/DisplayLikes.cshtml
@{
    ViewBag.Title = "Likes";
}

<h4>@ViewBag.LikeCount people like this post</h4>

@if (ViewBag.Likers.Count != 0)
{
    <ul>
        @foreach (var liker in ViewBag.Likers)
        {
            <li>
                @liker
            </li>        
        }

    </ul>
}

Cookbook/Views/Cookbook/DisplayRecipeFavorites.cshtml
@model List<string>
    <h4>My Favorites:</h4>

<ul class="nav nav-list" style="height: 100%">
    @if(Model.Count !=0)
    {
    foreach (var recipe in Model)
    {
        <li>
            @recipe
        </li>
    }
    }
    else
    {
        <b>You have not favorited any recipes yet. </b>
    }
</ul>

Cookbook/Views/Cookbook/Index.cshtml
@model List<Cookbook.Models.ViewPostModel>

<div class="row-fluid">
    <div class="span4" style="padding-left: 2em;">
        <div class="addPostRecipe">
            <ul class="nav nav-tabs" style="margin-bottom: 0px;">
                <li class="active"><a href="#post" data-toggle="tab">Create Recipe</a></li>
                <li><a href="#recipe" data-toggle="tab">Create Post</a></li>
            </ul>
            <div class="tabbable">
                <div class="tab-content">
                    <div class="tab-pane active" id="post">
                        @Html.Partial("UploadRecipe", new Cookbook.Models.UploadRecipeModel())
                        
                    </div>
                    <div class="tab-pane" id="recipe">
                        @Html.Partial("UploadPost", new Cookbook.Models.UploadBlogPostModel())
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span7">
        @foreach (var post in Model)
        {
            <br />
            <div class="row-fluid recipeOrPost">
                <div class="span4 offset1">
                    @{
                        string imageUrl = post.ImageURL;
                        if (imageUrl == null)
                        {
                            imageUrl = "http://newyork.cities2night.com/public/article_images/1281.jpg";
                        }
                    }
                    <img src=@imageUrl class="recipeImage" />
                </div>
                <div class="span1 divider">

                </div>
                <div class="span5">
                    <h4 class="recipeTitle">@post.Title</h4>
                    @if (post.RecipePost != null)
                    {
                        <p><strong>Ingredients:</strong></p>
                        foreach (var ingredient in post.RecipePost.Ingredients)
                        {
                            <p>@ingredient</p>
                        }

                        <p><strong>Instructions:</strong></p>
                        <p>@post.RecipePost.Instructions</p>
                        <p><b><a href="/Cookbook/DisplayRecipeLikes/?postId=@post.PostId">@post.RecipePost.LikeCount likes. </a></b>
                            @if (post.Liked == false)
                            {
                                <a href="/Cookbook/LikeRecipe/?postId=@post.PostId">Like</a>
                            }
                            else 
                            {
                                <a href="/Cookbook/UnlikeRecipe/?postId=@post.PostId">Unlike</a>
                            }
                        </p>
                        <p><b><a href="/Cookbook/DisplayFavorites/?postId=@post.PostId">@post.RecipePost.FavoriteCount favorites.</a></b>
                            @if (post.RecipePost.Favorited == false)
                            {
                                <a href="/Cookbook/FavoriteRecipe/?postId=@post.PostId">Favorite</a>
                            }
                            else
                            {
                                <a href="/Cookbook/UnfavoriteRecipe/?postId=@post.PostId">Unfavorite</a>
                            }
                        </p>
                    }
                    @if (post.BlogPost != null)
                    {
                        <p>@post.BlogPost.Post</p>
                        <p><b><a href="/Cookbook/DisplayBlogLikes/?postId=@post.PostId">@post.BlogPost.LikeCount Likes. </a></b>
                            @if (post.Liked == false)
                            {
                                <a href="/Cookbook/LikeBlog/?postId=@post.PostId">Like</a>
                            }
                            else
                            {
                                <a href="/Cookbook/UnlikeBlog/?postId=@post.PostId">Unlike</a>
                            }
                        </p>
                    }

                    <p><i>Posted on @post.DateCreated</i></p>

                </div>
            </div>
        }
        <div class="row-fluid span4 offset4">
            <ul class="pager">
            @if (ViewBag.Page > 1)
            {
                    <li class="previous">
                        @Html.ActionLink("← Newer", "Index", new { page = ViewBag.Page - 1 })
                    </li>
            }
            else
            {
                <li class="previous disabled">
                        <a href="#">← Newer</a>
                </li>
            }
            @if (ViewBag.Page < ViewBag.LastPage)
            {
                <li class="next">
                    @Html.ActionLink("Older →", "Index", new { page = ViewBag.Page + 1 })
                </li>
            }
            else
            {
                <li class="next disabled">
                    <a href="#">Older →</a>
                </li>
            }
            </ul>
        </div>
    </div>
</div>

Cookbook/Views/Cookbook/UploadPost.cshtml
@model Cookbook.Models.UploadBlogPostModel

@{
    ViewBag.Title = "Upload Post";
}
<div class="well">
    @using (Html.BeginForm("UploadPost", "Cookbook", FormMethod.Post,
        new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()

        <fieldset>
                    @Html.LabelFor(m => m.Title)
                    @Html.TextBoxFor(m => m.Title)
            <br />
                    @Html.LabelFor(m => m.Post)
                    @Html.TextBoxFor(m => m.Post)
            <br />
                    @Html.LabelFor(m => m.Tags)
                    @Html.TextBoxFor(m => m.Tags)
            <br />

            <label for="File">Picture:</label>
            <input type="file" name="File" id="File" accept="image/*"/>
            <br />
            <br />
            <button type="submit" class="btn btn-primary">Upload Post</button>
        </fieldset>

    }        
</div>

Cookbook/Views/Cookbook/UploadRecipe.cshtml
@model Cookbook.Models.UploadRecipeModel

@{
    ViewBag.Title = "Upload Recipe";
}

<div class="well">
    @using (Html.BeginForm("UploadRecipe", "Cookbook", FormMethod.Post,
        new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()

        <fieldset>
            @Html.LabelFor(m => m.Title)
            @Html.TextBoxFor(m => m.Title)
            <br />
            @Html.LabelFor(m => m.Ingredients)
            @Html.EditorFor(m => m.Ingredients)
            <br />
            @Html.LabelFor(m => m.Instructions)
            @Html.EditorFor(m => m.Instructions, new { cols = 35, rows = 10 })
            <br />
            @Html.LabelFor(m => m.Tags)
            @Html.TextBoxFor(m => m.Tags)
            <br />

            <label for="File">Picture:</label>
            <input type="file" name="File" id="File" accept="image/*"/>
            <br />
            <br />
            <button type="submit" class="btn btn-primary">Upload Recipe</button>
        </fieldset>
    }
</div>

Cookbook/Views/Cookbook/ViewCookbook.cshtml
@model List<Cookbook.Models.ViewPostModel>

<div class="row-fluid">
    <div class="span4 offset1 well profilePic" style="text-align:center;">
        <img src="~/Content/images/defaultUser.png" />
        <h3>@ViewBag.Username</h3>
        <p>
            @if(!ViewBag.IsSubscribed)
            {
                @Html.ActionLink("Subscribe", "AddSubscriber", "Subscribe", new { userId = ViewBag.UserId }, new { })
            }
            else
            {
                @Html.ActionLink("Unsubscribe", "RemoveSubscriber", "Subscribe", new { userId = ViewBag.UserId }, new { })
            }
        </p>
    </div>
    <div class="span7">
        @foreach (var post in Model)
        {
            <br />
            <div class="row-fluid recipeOrPost">
                <div class="span4 offset1">
                    @{
                        string imageUrl = post.ImageURL;
                        if (imageUrl == null)
                        {
                            imageUrl = "http://newyork.cities2night.com/public/article_images/1281.jpg";
                        }
                    }
                    <img src=@imageUrl class="recipeImage" />
                    <h4>@ViewBag.Username</h4>
                </div>
                <div class="span1 divider">

                </div>
                <div class="span5">
                    <h4 class="recipeTitle">@post.Title</h4>
                    @if (post.RecipePost != null)
                    {
                        <p><strong>Ingredients:</strong></p>
                        foreach (var ingredient in post.RecipePost.Ingredients)
                        {
                            <p>@ingredient</p>
                        }

                        <p><strong>Instructions:</strong></p>
                        <p>@post.RecipePost.Instructions</p>
                        <p><b><a href="/Cookbook/DisplayRecipeLikes/?postId=@post.PostId">@post.RecipePost.LikeCount Likes. </a></b>
                            @if (post.Liked == false)
                            {
                                <a href="/Cookbook/LikeRecipe/?postId=@post.PostId">Like</a>
                            }
                            else 
                            {
                                <a href="/Cookbook/UnlikeRecipe/?postId=@post.PostId">Unlike</a>
                            }
                        </p>
                        <p><b><a href="/Cookbook/DisplayFavorites/?postId=@post.PostId">@post.RecipePost.FavoriteCount favorites.</a></b>
                            @if (post.RecipePost.Favorited == false)
                            {
                                <a href="/Cookbook/FavoriteRecipe/?postId=@post.PostId">Favorite</a>
                            }
                            else
                            {
                                <a href="/Cookbook/UnfavoriteRecipe/?postId=@post.PostId">Unfavorite</a>
                            }
                        </p>
                    }
                    @if (post.BlogPost != null)
                    {
                        <p>@post.BlogPost.Post</p>
                        <p><b><a href="/Cookbook/DisplayBlogLikes/?postId=@post.PostId">@post.BlogPost.LikeCount Likes. </a></b>
                            @if (post.Liked == false)
                            {
                                <a href="/Cookbook/LikeBlog/?postId=@post.PostId">Like</a>
                            }
                            else
                            {
                                <a href="/Cookbook/UnlikeBlog/?postId=@post.PostId">Unlike</a>
                            }
                        </p>
                    }
                    <p><i>Posted on @post.DateCreated</i></p>

                </div>
            </div>
        }
        <span>
        @if (ViewBag.Page > 1)
        {
            @Html.ActionLink("Previous", "ViewCookbook", new { page = ViewBag.Page - 1, userId = ViewBag.UserId }, new { })
        }
        @if (ViewBag.Page > 1 && ViewBag.Page < ViewBag.LastPage)
        {
            <span>|</span>
        }
        @if (ViewBag.Page < ViewBag.LastPage)
        {
            @Html.ActionLink("Next", "ViewCookbook", new { page = ViewBag.Page + 1 , userId = ViewBag.UserId }, new { })
        }
    </span>
    </div>
</div>